name: RSpec tests

on:
  push:
    branches: [ master, fix-ci ]
  pull_request:
    branches: [ master ]

jobs:
  ruby:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
       include:
         - docker-image: 'library/ruby:2.5'
         - docker-image: 'library/ruby:2.6'
         - docker-image: 'library/ruby:2.7'
         - docker-image: 'library/ruby:3.0'
         - docker-image: 'library/ruby:3.1'
         - docker-image: 'bitnami/jruby:latest'
    container: ${{ matrix.docker-image }}
    steps:
    - uses: actions/checkout@v2
    - name: Install bundler ${{ matrix.bundler-version }}
      run: gem install bundler ${{ matrix.bundler-version && format('{0} {1}', '-v', matrix.bundler-version) || '' }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
      continue-on-error: ${{ contains(matrix.docker-image, 'jruby') }}
  actionmailer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
        bundler-cache: true
    - name: Setup mail with ActionMailer edge
      run: |
        git clone --depth=1 https://github.com/rails/rails.git -b main
        cd rails
        echo -e "\ngem 'mail', path: '../'" >> Gemfile
        bundle update --bundler --source mail
    - name: Run ActionMailer tests
      run: |
        cd rails/actionmailer
        bundle exec rake
